server:
  port: 10010
spring:
  application:
    name: springcloud-demo-gateway-zuul
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/