spring:
  application:
    name: springcloud-demo-security-oauth2-jwt
  
server:
  context-path: /
  port: 8761

management:
  context-path: /admin

security:
  user:
    name: fangj
    password: p@ssw1r4
    role:
    - USER,ADMIN

      