spring:
  application:
    name: springcloud-demo-provider-sleuth
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:oracle:thin:@10.5.1.13:1521:fnd
    username: bp_dev
    password: bp_dev
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
management:
  security:
    enabled: false

#desc for swagger2 api 
app:
  api:
    title: spring-cloud-demo-provider
    desc: docs for spring cloud demo provider
    version: v1.0 

server:
  context-path: /
  port: 9091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
