spring:
  application:
    name: springcloud-demo-provider-sleuth-zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:oracle:thin:@10.5.1.121:1521:hhuat
    username: bphh
    password: hhic1221
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
management:
  security:
    enabled: false

#desc for swagger2 api 
app:
  api:
    title: springcloud-demo-provider-sleuth-zipkin
    desc: docs for spring cloud demo provider
    version: v1.0 

server:
  context-path: /
  port: 9010

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
