spring:
  application:
    name: springcloud-demo-consumer-feign-hystrix
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  context-path: /
  port: 8081

feign:
  hystrix:
    enabled: true

endpoints:
  health:
    sensitive: true
management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/